<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>
  <meta charset="utf-8" />
  <meta name="generator" content="pandoc" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes" />
  <title>jsErrors</title>
  <style type="text/css">
      code{white-space: pre-wrap;}
      span.smallcaps{font-variant: small-caps;}
      span.underline{text-decoration: underline;}
      div.column{display: inline-block; vertical-align: top; width: 50%;}
  </style>
</head>
<body>
<h1 id="javascript-errors">JavaScript Errors</h1>
<h2 id="our-main-focus">Our main focus:</h2>
<ul>
<li>SyntaxError - represents an error in the syntax of the code.</li>
<li>ReferenceError - represents an error thrown when an invalid reference is made.</li>
<li>TypeError - represents an error when a variable or parameter is not of a valid type.</li>
</ul>
<h2 id="other-types-of-errors">Other types of errors:</h2>
<ul>
<li>RangeError - representing an error for when a numeric variable or parameter is outside of its valid range.</li>
<li>InternalError - represents an error in the internal JavaScript engine.</li>
<li>EvalError - represents an error with the global eval function.</li>
<li>URIError - represents an error that occurs when encodeURI() or decodeURI() are passed invalid parameters.</li>
</ul>
<h2 id="catching-errors">Catching Errors</h2>
<h3 id="try-catch">try &amp; catch</h3>
<p>If we wanted to throw an error without stopping program execution we can use a try…catch block.</p>
<p>Syntax:</p>
<pre><code>try {
  // statements that will be attempted to here
} catch (error) {
  // if an error is thrown it will be &quot;caught&quot;
  // allowing the program to continue execution
  // these statements will be run and the program will continue!
}</code></pre>
<p>Note: * We normally use try…catch blocks with functions that might throw an error. * We can use console.error instead of console.log to make logged errors more noticeable.</p>
<p>Ex:</p>
<pre><code>function safeDivide(a, b) {
  if (b === 0) {
    throw new Error(&quot;cannot divide by zero&quot;);
  } else {
    return a / b;
  }
}

try {
  console.log(safeDivide(30, 5)); // prints 6
} catch (error) {
  console.error(error.name + &quot;: &quot; + error.message);
}

console.log(&quot;hello&quot;); // prints hello</code></pre>
<h2 id="syntax-errors">Syntax Errors</h2>
<p>A SyntaxError is thrown when the JavaScript engine attempts to parse code that does not conform to the syntax of the JavaScript language.</p>
<p>Ex: When learning the JavaScript language this error is a constant companion for any missing } or misspelled function keywords.</p>
<pre><code>  funtion broken () { // Uncaught SyntaxError: Unexpected identifier
    console.log(&quot;I&#39;m broke&quot;)
  }

  function broken () { // Uncaught SyntaxError: Unexpected identifier
    console.log(&quot;I&#39;m broke&quot;)
  }} // Uncaught SyntaxError: Unexpected token &#39;}&#39;</code></pre>
<ul>
<li>Note: One thing to note about Syntax Errors is that many of them can’t be caught using try catch blocks.</li>
</ul>
<h2 id="reference-errors">Reference Errors</h2>
<p>1- “The ReferenceError object represents an error when a non-existent variable is referenced.” - MDN</p>
<p>Ex:</p>
<pre><code>  function callPuppy() {
    const puppy = &quot;puppy&quot;;
    console.log(pupy);
  }

callPuppy(); // ReferenceError: pupy is not defined</code></pre>
<p>2- Another common cause for a thrown ReferenceError is attempting to access a variable that is not in scope.</p>
<p>Ex:</p>
<pre><code>  function callPuppy() {
    const puppy = &quot;puppy&quot;;
  }

  console.log(puppy); // ReferenceError: puppy is not defined</code></pre>
<h2 id="typeerror">TypeError</h2>
<p>When an operation cannot be performed because the operand is a value of the wrong type.</p>
<p>Ex:</p>
<pre><code>  let dog; // Remember unassigned variables are undefined!
  dog(); // TypeError: dog is not a function</code></pre>
<p>When you are attempting to modify a value that cannot be changed.</p>
<p>Ex:</p>
<pre><code>  const puppy = &quot;puppy&quot;;
  puppy = &quot;apple&quot;; // TypeError: Assignment to constant variable.</code></pre>
<h2 id="custom-errors">Custom Errors</h2>
<p>we can use the Error constructor to create new Error object instances. We can optionally supply a message, fileName and lineNumber where the error occurred.</p>
<p>Syntax:</p>
<pre><code>new Error([message[, fileName[, lineNumber]]])</code></pre>
<p>Note: * The Error constructor is also somewhat unique in that you can call it with or without the new keyword and it will return a new Error object:</p>
<p>Ex:</p>
<pre><code>const first = Error(&quot;I am an error object!&quot;);
const second = new Error(&quot;I am too an error object!&quot;);

console.log(first); // Error: I am an error object!
console.log(second); // Error: I am too an error object!</code></pre>
</body>
</html>
