<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>
  <meta charset="utf-8" />
  <meta name="generator" content="pandoc" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes" />
  <title>d2-promises-notes</title>
  <style type="text/css">
      code{white-space: pre-wrap;}
      span.smallcaps{font-variant: small-caps;}
      span.underline{text-decoration: underline;}
      div.column{display: inline-block; vertical-align: top; width: 50%;}
  </style>
</head>
<body>
<h1 id="async-sync-review">ASYNC / SYNC REVIEW</h1>
<p>synchronous - execution of additional JS code must wait until current command completes (blocking) - there is an inherent order</p>
<p>asynchronous - can continue to execute another command even if current hasnt completed (non blocking) - may not be guarenteed order - ex: fetching from an api, querying database, settimeout, setinterval</p>
<p>JS is single threaded - handles new events only after current command has completed - at any instance in program, only one command is executing</p>
<p>Call Stack - structure used to track current function queues - tracks current task in progress - where JS code is pushed and executed one by one - if statement is async, code is forwarded to message queue</p>
<p>Message Queue - structure used to track handling of events (messages) - “waiting line for events” - new items added to back of line (enqueue) - items removed from front of line (dequeue) - add message to queue when event occurs - ex: when setimeout invokes callback - begin processing events when call stack is empty - added one by one to callstack</p>
<p>Event Loop - model of execution JS uses - consists of call stack and message queue - continuously adds messages from message queue to stack once stack is empty</p>
<p>asynchronous non-blocking Input/Output model - JS uses callback mechanism to prevent blocking of main thread on I/O operations - async operations specify a callback - cb is func to be executed when result of async operation is ready - callback added to message queue - processed when stack is empty</p>
<p>“JavaScript Callback Hell” - when result of cb makes another async call, we must nest callbacks - must also handle errors for each I/O opertaion - nested error handling and callbacks makes code hard to read</p>
<pre><code>function grindTheBeans(nextTask) {
  setTimeout(() =&gt; {
    console.log(&#39;done grinding the coffee beans&#39;);
    nextTask();
  }, 1000)
}

function heatTheWater(nextTask) {
  setTimeout(() =&gt; {
    console.log(&#39;done heating the water&#39;);
    nextTask();
  }, 500)
}

function addBeansToWater(nextTask) {
  setTimeout(() =&gt; {
    console.log(&#39;done adding beans to water&#39;);
    nextTask();
  }, 1000)
}

// callback craziness

function makeCoffee() {
    grindTheBeans(() =&gt; {
        heatTheWater(() =&gt; {
            addBeansToWater(() =&gt; {
                console.log(&#39;coffee is ready, enjoy&#39;)
            })
        })
    })
}

makeCoffee()</code></pre>
<h1 id="promises">PROMISES</h1>
<p>Overview - introduced in 2015 to encourage writing async code, in a way that appears synch - issue with async code is it can be hard to figure out when everything is happening</p>
<p>The Problem - issue with async code is there is no guareenteed order - what if we want one async task to start only when another async task has completed?</p>
<p>The Callback Solution - could use callbacks to solve the issue - pass each step to previous step as a callback - allows us to specify order asyc funcs are invoked - issue: nested callbacks become difficult to read</p>
<p>The Promise Solution - promise: object that may produce a single value some time in the future, either: - resolved value (like reading a file or getting JSON from a Web site) - reason that it’s not resolved (i.e file doesn’t exist or the Web site is down) - can attach callbacks to handle the fulfilled value or the reason for rejection</p>
<p>Promises - receives callback parameter that accepts two callbacks as arguments: 1. resolve: invoked when async operaataion waas successful 2. reject: called whenever an error has occurred - promises are eager: - starts executing code inside as soon as the promise constructor is invoked</p>
<pre><code>let promise = new Promise((resolve, reject) =&gt; {
    // some async code would go here
    resolve();
})</code></pre>
<p>Promises have 3 states 1. Pending: The Promise obj has not been resolved yet 2. Fulfilled: Whatever operation the Promise represented succeeded and your success handler will get called 3. Rejected: Whatever operation the Promise represented failed and your error handler will get called</p>
<p>Promise objects have the following methods available on them: 1. <code>then(successHandler, errorHandler)</code> 2. <code>catch(errorHandler)</code> - ways to handle promise when it leaves pending state - handle the state change from pending to either fulfilled or rejected</p>
<p>Success Handler: function that has one parameter, the value that a fulfilled Promise has Error Handler: function that has one parameter, the reason that the Promise failed</p>
<pre><code>const { readFile } = require(&quot;fs&quot;);

function readFilePromise(path) {
    return new Promise((resolve, reject) =&gt; {
        // third argument is callback function
        // cb is invoked when file has been read 
        readFile(path, &#39;utf8&#39;, (err, content) =&gt; {
            if (err) {
                // if error occurs, promise is rejected
                reject(err)
            } else {
                // if no error, promise resolves with content as value
                resolve(content);
            }
        })
    })
}

// readFilePromise returns a promise so can chain .then
readFilePromise(&#39;manifest.txt&#39;)
    // if promise is fulfilled, code in .then is executed
    .then(manifest =&gt; {
        const fileList = manifest.split(&#39;\n&#39;);
        console.log(&#39;Reading&#39;, fileList.length, &#39;files&#39;);
    });</code></pre>
<p>above code is okay but still difficult to read…</p>
<h1 id="chaining-thens">Chaining <code>then</code>s</h1>
<ul>
<li><p>Each Promise has a then method that handles what happens when the Promise transitions out of the pending state</p></li>
<li><p>Each then method returns a Promise that transitions out of its pending state when the then that created it completes</p></li>
<li><p>ability to break apart the two lines of the success handler in the previous example to two one-line functions that do the same thing with less code</p>
<p>// Get a Promise that fulfills when the file is read // with the value of the content of the file. const filePromise = readFilePromise(“manifest.txt”);</p>
<p>// Register a success handler that takes the fulfilled // value of the filePromise in the parameter named “manifest”, // which is the content of the file, split it on newline // characters, and return a Promise whose fulfilled value is // list of lines. const fileListPromise = filePromise.then(manifest =&gt; manifest.split(“”));</p>
<p>// Register a success handler to the fileListPromise that // receives the fulfilled value in the “fileList” parameter // and returns a Promise whose fulfilled value is the length // of the fileList array. const lengthPromise = fileListPromise.then(fileList =&gt; fileList.length);</p>
<p>// Register a success handler to the lengthPromise that // receives the fulfilled value in the “numberOfFiles” parameter // and uses it to print the number of files to be read. lengthPromise.then(numberOfFiles =&gt; console.log(“Reading”, numberOfFiles, “files”) );</p></li>
</ul>
<p>What is happening? - Each call to then creates a new Promise object - Each promise resolves to value of output returned from previous success handler</p>
<h1 id="handling-failure-with-then---incorrectly">Handling failure with <code>then</code> - Incorrectly</h1>
<pre><code>readFilePromise(&quot;manifest.txt&quot;)
  .then(
        // success handler
        manifest =&gt; manifest.split(&quot;\n&quot;),
        // error handler
    reason =&gt; console.err(&quot;Badness happened&quot;, reason)
  )
  .then(fileList =&gt; fileList.length)
    .then(numberOfFiles =&gt; console.log(&quot;Reading&quot;, numberOfFiles, &quot;files&quot;));
    </code></pre>
<p>if error occurs: 1. first Promise object goes into rejected state 2. err reason gets passed to the first <code>then</code> 3. err is printed 4. second promise is fulfilled b/c err handler completes w/o any issues 5. promise returned by first then does not get rejected 6. third promise resolves with value returned by <code>console.err</code> which is undefined 7. second then relies on obj with length prop =&gt; undefined doesnt so exception raised 8. causes promise returned by second then to be rejected 9. b/c promise is rejected, third then will try to run error handler but there isn’t one 10. in browser nothing happens, in node <code>UnhandledPromiseRejectionWarning</code></p>
<h1 id="handling-failure-with-then---correctly">Handling failure with <code>then</code> - Correctly</h1>
<pre><code>readFilePromise(&quot;manifest.txt&quot;)
  .then(manifest =&gt; manifest.split(&quot;\n&quot;))
  .then(fileList =&gt; fileList.length)
  .then(
    numberOfFiles =&gt; console.log(&quot;Reading&quot;, numberOfFiles, &quot;files&quot;),
    reason =&gt; console.err(&quot;Badness happened&quot;, reason)
  );</code></pre>
<p>if error occurs: 1. First then: I do not have an error handler. I will pass the error on and not run the success handler. 2. Second then: I do not have an error handler. I will pass the error on and not run the success handler. 3. Third then: I have an error handler and will run it.</p>
<p>code looks better but besides double handler code when passing in two funcs</p>
<h1 id="handling-failure-with-catch">Handling failure with <code>catch</code></h1>
<p>solution to design issue - <code>then</code> can handle success and failure - successHandler is called with value of the operation of the Promise when Promise is fulfilled - errorHandler is called when error condition occurs, passing along the reason - if Promise is rejected and no error handler exists, then that <code>then</code> is skipped - if errorHandler is called and does not raise an exception, next Promise is fulfilled and successHandler called</p>
<pre><code>readFilePromise(&quot;manifest.txt&quot;)
  .then(manifest =&gt; manifest.split(&quot;\n&quot;))
  .then(fileList =&gt; fileList.length)
  .then(numberOfFiles =&gt; console.log(&quot;Reading&quot;, numberOfFiles, &quot;files&quot;))
  .catch(reason =&gt; console.err(&quot;Badness happened&quot;, reason));</code></pre>
<p>catch acts like an errorHandler - if it doesnt throw an exception, then it returns a Promise in fullfilled state with whatever return value is</p>
<h1 id="using-promise.all-for-many-future-values">Using <code>Promise.all</code> for many future values</h1>
<p>Imagine we have 3 files we want to read with <code>readFilePromise</code> method - want to wait until all three are done - want them to read files simultaniously - how to manage 3 promises at once?</p>
<pre><code>const values = [
  readFilePromise(&quot;file-boop.txt&quot;), // this is a Promise object: pending
  readFilePromise(&quot;file-doop.txt&quot;), // this is a Promise object: pending
  readFilePromise(&quot;file-goop.txt&quot;), // this is a Promise object: pending
];

const superPromise = Promise.all(values);</code></pre>
<p>superPromise is a Promise object in pending state - inside is an array of Promise objects in pending statese - if any promise transitioned to rejeceted, then superPromise is rejected immediately - superPromisee has same reason as inner Promise failed with - when all 3 Promise objects transition are fulfilled, so will superPromise - value will be array of all the resolved values of original array</p>
<pre><code>superPromise
  .then(values =&gt; console.log(values))
  .catch(reason =&gt; console.error(reason));</code></pre>
<p>if function successfully reads file - values passed to <code>then</code> come from values inside superPromise - values = content of file-boop.txt, file-doop.txt, file-goop.txt</p>
<p>if something goes wrong - <code>catch</code> is called with the error reason from Promise obj that first failed</p>
<p><code>Promise.all</code> - accepts array of values - returns a new Promise obj in pending state - converts all non-Promise values into Promise obj that are immed. fulfilled - if any Promise transitions to rejected, superPromise is rejected with same reason - if all inner promises fullfilled, superpromise transitions to fulfilled - value is array populatedk in order, of resolved values of original array</p>
<h1 id="flattening-promises">Flattening Promises</h1>
<h1 id="error-handling">Error Handling</h1>
<p>problems with below code - an error originating in save() will be caught by handleError - an error originating in handleSuccess() will be swallowed - promise returned from .then() will be rejected</p>
<pre><code>  save().then(
    handleSuccess,
    handleError
  );</code></pre>
<p>below code is better because - catch will handle rejections from either save() or handleSucces()</p>
<pre><code>  save()
    .then(handleSuccess)
    .catch(handleError)
  ;</code></pre>
<p>what if you want errors to be handled differently?</p>
<pre><code>  save()
    .then(
      handleSuccess,
      handleSaveError
    )
    .catch(handleSuccessError)
  ;</code></pre>
<p>best practice to always have a .catch()</p>
</body>
</html>
